# Changes here will be overwritten by Copier
_commit: v3.7.4
_src_path: https://github.com/stkr22/copier-python-project.git
author_email: stkr22@github.com
author_full_name: stkr22
codeowner_username: '@stkr22'
copyright_license: GPL-3.0-only
github_repository_name: private-assistant-intent-engine-py
github_username: stkr22
project_description: Intent engine for the private assistant ecosystem
project_name: Private Assistant Intent Engine
publish_to_pypi: false
python_package_distribution_name: private-assistant-intent-engine
python_package_import_name: private_assistant_intent_engine
python_package_version: 0.5.0
use_containers: true
