# Changes here will be overwritten by Copier
_commit: 1.1.6
_src_path: https://github.com/stkr22/copier-python-project.git
author_email: stkr22@github.com
author_full_name: stkr22
codeowner_username: '@stkr22'
copyright_license: GNU General Public License v3.0
project_description: Intent engine for the private assistant ecosystem
project_name: Private Assistant Intent Engine
python_package_distribution_name: private-assistant-intent-engine
python_package_import_name: private_assistant_intent_engine
version: 0.0.1
